In [1]:
pip install numpy pandas matplotlib seaborn scikit-learn jupyter

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [4]:
df.head()

,color
0,red
1,blue
2,green
3,green
4,red


In [5]:
encoder=OneHotEncoder()

In [6]:
encoded = encoder.fit_transform(df[['color']]).toarray()

In [7]:
import pandas as pd

encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [8]:
encoder_df

,color_blue,color_green,color_red
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,1.0,0.0
4,0.0,0.0,1.0
5,1.0,0.0,0.0


In [9]:
encoder.transform([['blue']]).toarray()

d:\ML\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [10]:
pd.concat([df,encoder_df],axis=1)

,color,color_blue,color_green,color_red
0,red,0.0,0.0,1.0
1,blue,1.0,0.0,0.0
2,green,0.0,1.0,0.0
3,green,0.0,1.0,0.0
4,red,0.0,0.0,1.0
5,blue,1.0,0.0,0.0


In [11]:
df.head()

,color
0,red
1,blue
2,green
3,green
4,red


In [12]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [13]:
lbl_encoder.fit_transform(df[['color']])

d:\ML\venv\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [14]:
lbl_encoder.transform([['red']])

d:\ML\venv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

Ordinal Encoding


###

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
df = pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [18]:
df

,size
0,small
1,medium
2,large
3,medium
4,small
5,large


In [19]:
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [20]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

Target Gudied Ordinal Encoding

In [22]:
import pandas as pd

df = pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York' , 'Paris'],
    'price':[200,150,300,250,180,320]
})

In [23]:
mean_price =df.groupby('city')['price'].mean().to_dict()

In [24]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [25]:
df['city_encoded']= df['city'].map(mean_price)

In [33]:
import seaborn as sns

df1=sns.load_dataset('tips')
print(df1)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


In [31]:
df1.groupby('time')['total_bill'].mean().to_dict()

C:\Users\nitai\AppData\Local\Temp\ipykernel_10676\4245761295.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df1.groupby('time')['total_bill'].mean().to_dict()


{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}